# Generated by Django 5.0.3 on 2024-03-25 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacherinfos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enseignant',
            name='Adresse',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='DateNaissance',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='Email',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='Etablissement',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='Fonction',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='Grade',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='Matricule',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='MotDePasse',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='Nom',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='NumeroTelephone',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='Prénom',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
