# Generated by Django 5.0.3 on 2024-03-26 00:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacherinfos', '0002_enseignant_adresse_enseignant_datenaissance_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='enseignant',
            table='Enseignant',
        ),
    ]
