# Generated by Django 5.0.3 on 2024-03-26 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacherinfos', '0003_alter_enseignant_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignant',
            name='id',
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='Matricule',
            field=models.CharField(blank=True, max_length=20, primary_key=True, serialize=False),
        ),
    ]
