# Generated by Django 5.0.3 on 2024-03-26 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacherinfos', '0004_remove_enseignant_id_alter_enseignant_matricule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='enseignant',
            name='Matricule',
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='Fonction',
            field=models.CharField(blank=True, choices=[('y', 'Yes'), ('n', 'No'), ('u', 'Unknown')], max_length=20),
        ),
        migrations.AddField(
            model_name='enseignant',
            name='matricule',
            field=models.CharField(blank=True, max_length=20, primary_key=True, serialize=False),
        ),
    ]
