# Generated by Django 5.0.3 on 2024-03-26 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacherinfos', '0005_remove_enseignant_matricule_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enseignant',
            old_name='matricule',
            new_name='Matricule',
        ),
    ]
