# Generated by Django 5.0.3 on 2024-03-26 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacherinfos', '0006_rename_matricule_enseignant_matricule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='Fonction',
            field=models.CharField(choices=[('FR', 'Freshman'), ('SO', 'Sophomore'), ('JR', 'Junior'), ('SR', 'Senior'), ('GR', 'Graduate')], default='FR', max_length=2),
        ),
    ]
