# Generated by Django 5.0.3 on 2024-03-26 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacherinfos', '0007_alter_enseignant_fonction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='Fonction',
            field=models.CharField(blank=True, choices=[('f1', 'function1'), ('f2', 'function2'), ('f3', 'function3')], max_length=20),
        ),
    ]
