# Generated by Django 5.0.3 on 2024-03-26 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacherinfos', '0009_alter_enseignant_fonction'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Enseignant',
            new_name='Enseigne',
        ),
    ]
