# Generated by Django 5.0.3 on 2024-03-26 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacherinfos', '0010_rename_enseignant_enseigne'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('test1', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('test2', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'test',
            },
        ),
    ]
