# Generated by Django 5.0.3 on 2024-03-26 17:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacherinfos', '0012_delete_enseigne'),
    ]

    operations = [
        migrations.DeleteModel(
            name='test',
        ),
    ]
