# Generated by Django 5.0.3 on 2024-03-26 17:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacherinfos', '0014_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Enseignant',
        ),
    ]
