# Generated by Django 5.0.3 on 2024-03-26 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacherinfos', '0016_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='Fonction',
            field=models.CharField(choices=[('rd', 'red'), ('bl', 'blue')], max_length=20),
        ),
    ]
