# Generated by Django 5.0.3 on 2024-03-26 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacherinfos', '0017_alter_enseignant_fonction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Module',
            fields=[
                ('Code', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('NomModule', models.CharField(blank=True, max_length=20)),
                ('Coefficient', models.IntegerField(blank=True)),
                ('NbrHeures', models.IntegerField(blank=True)),
                ('Semestre', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'Module',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('NomPromo', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('Departement', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'Promotion',
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('NomSalle', models.CharField(blank=True, max_length=20)),
                ('IdSalle', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('Zone', models.CharField(blank=True, max_length=20)),
                ('NbrPlaces', models.IntegerField(blank=True)),
                ('Type', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'Salle',
            },
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='Email',
            field=models.EmailField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='Fonction',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.CreateModel(
            name='Enseigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Matricule', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Teacherinfos.enseignant')),
                ('Code', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Teacherinfos.module')),
            ],
            options={
                'db_table': 'Enseigne',
            },
        ),
        migrations.AddField(
            model_name='module',
            name='nomP',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Teacherinfos.promotion'),
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('IdSeance', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('Type', models.CharField(blank=True, max_length=20)),
                ('Jour', models.CharField(blank=True, max_length=20)),
                ('HeureDebut', models.TimeField(blank=True)),
                ('HeureFin', models.TimeField(blank=True)),
                ('Presence', models.BooleanField()),
                ('Semestre', models.CharField(blank=True, max_length=20)),
                ('Date', models.DateField(blank=True)),
                ('Code', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Teacherinfos.module')),
                ('Matricule', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Teacherinfos.enseignant')),
                ('idSalle', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Teacherinfos.salle')),
            ],
            options={
                'db_table': 'Seance',
            },
        ),
        migrations.CreateModel(
            name='heure',
            fields=[
                ('idHeure', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('defType', models.CharField(blank=True, max_length=20)),
                ('idSeance', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Teacherinfos.seance')),
            ],
            options={
                'db_table': 'Heure',
            },
        ),
        migrations.CreateModel(
            name='section',
            fields=[
                ('idSection', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('NomSection', models.CharField(blank=True, max_length=20)),
                ('nomP', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Teacherinfos.promotion')),
            ],
            options={
                'db_table': 'Section',
            },
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('idGroupe', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('Numero', models.IntegerField(blank=True)),
                ('Specialite', models.CharField(blank=True, max_length=20)),
                ('idSection', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Teacherinfos.section')),
            ],
            options={
                'db_table': 'Groupe',
            },
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('idSpecialite', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('NomSpecialite', models.CharField(blank=True, max_length=20)),
                ('idSection', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Teacherinfos.section')),
            ],
            options={
                'db_table': 'Specialite',
            },
        ),
        migrations.CreateModel(
            name='SpecPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idSpecialite', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Teacherinfos.specialite')),
                ('nomP', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Teacherinfos.promotion')),
            ],
            options={
                'db_table': 'SpecPromo',
            },
        ),
    ]
