# Generated by Django 5.0.3 on 2024-03-26 23:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacherinfos', '0018_module_promotion_salle_alter_enseignant_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='Numero',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4')], max_length=20),
        ),
    ]
