# Generated by Django 5.0.3 on 2024-03-26 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacherinfos', '0019_alter_groupe_numero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='Fonction',
            field=models.CharField(choices=[('Fonction1', 'Fonction1'), ('Fonction2', 'Fonction2')], max_length=20),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='Grade',
            field=models.CharField(choices=[('MCA', 'MCA'), ('MCB', 'MCB')], max_length=50),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='Numero',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], max_length=20),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='Specialite',
            field=models.CharField(choices=[('ISI', 'ISI'), ('SIW', 'SIW'), ('IASD', 'IASD')], max_length=20),
        ),
        migrations.AlterField(
            model_name='heure',
            name='defType',
            field=models.CharField(choices=[('HeuresSup', 'HeuresSup'), ('Charge', 'Charge')], max_length=20),
        ),
        migrations.AlterField(
            model_name='module',
            name='Semestre',
            field=models.CharField(choices=[('S1', 'S1'), ('S2', 'S2')], max_length=20),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='Departement',
            field=models.CharField(choices=[('Classe préparatoire', 'Classe préparatoire'), ('Seconde Cycle', 'Seconde Cycle')], max_length=20),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='NomPromo',
            field=models.CharField(choices=[('1CPI', '1CPI'), ('2CPI', '2CPI'), ('1CS', '1CS'), ('2CS', '2CS'), ('3CS', '3CS')], max_length=20, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='salle',
            name='Type',
            field=models.CharField(choices=[('Amphi', 'Amphi'), ('SalleTd', 'SalleTd'), ('SalleTp', 'SalleTp')], max_length=20),
        ),
        migrations.AlterField(
            model_name='seance',
            name='Semestre',
            field=models.CharField(choices=[('S1', 'S1'), ('S2', 'S2')], max_length=20),
        ),
        migrations.AlterField(
            model_name='seance',
            name='Type',
            field=models.CharField(choices=[('Cours', 'Cours'), ('Td', 'Td'), ('Tp', 'Tp')], max_length=20),
        ),
        migrations.AlterField(
            model_name='section',
            name='NomSection',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=20),
        ),
        migrations.AlterField(
            model_name='specialite',
            name='NomSpecialite',
            field=models.CharField(choices=[('ISI', 'ISI'), ('SIW', 'SIW'), ('IASD', 'IASD')], max_length=20),
        ),
    ]
