# Generated by Django 5.0.3 on 2024-03-26 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacherinfos', '0020_alter_enseignant_fonction_alter_enseignant_grade_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='Grade',
            field=models.CharField(choices=[('MCA', 'MCA'), ('MCB', 'MCB'), ('Teacher', 'Teacher'), ('LectureA', 'LectureA'), ('LectureB', 'LectureB'), ('Professor', 'Professor')], max_length=50),
        ),
    ]
