# Generated by Django 5.0.3 on 2024-03-27 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacherinfos', '0021_alter_enseignant_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='NomS',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='Specialite',
            field=models.CharField(blank=True, choices=[('ISI', 'ISI'), ('SIW', 'SIW'), ('IASD', 'IASD')], max_length=20),
        ),
        migrations.AlterField(
            model_name='specialite',
            name='NomSpecialite',
            field=models.CharField(blank=True, choices=[('ISI', 'ISI'), ('SIW', 'SIW'), ('IASD', 'IASD')], max_length=20),
        ),
    ]
