# Generated by Django 5.0.3 on 2024-03-27 19:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacherinfos', '0023_rename_code_enseigne_codee_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seance',
            name='Date',
        ),
    ]
