# Generated by Django 5.0.3 on 2024-03-27 19:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacherinfos', '0024_remove_seance_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='Date',
            field=models.DateField(blank=True, default=None),
        ),
    ]
