# Generated by Django 5.0.3 on 2024-03-27 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacherinfos', '0025_seance_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abcence',
            fields=[
                ('IdAbs', models.AutoField(primary_key=True, serialize=False)),
                ('DateAbs', models.DateField(default=None)),
                ('HeureDebut', models.TimeField(blank=True)),
                ('HeureFin', models.TimeField(blank=True)),
                ('Motif', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'db_table': 'Absence',
            },
        ),
        migrations.AlterUniqueTogether(
            name='enseigne',
            unique_together={('Matric', 'Codee')},
        ),
        migrations.AlterUniqueTogether(
            name='specpromo',
            unique_together={('idSpecialite', 'nomP')},
        ),
    ]
