# Generated by Django 5.0.3 on 2024-03-27 20:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacherinfos', '0026_abcence_alter_enseigne_unique_together_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='abcence',
            name='IdProf',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Teacherinfos.enseignant'),
        ),
    ]
