# Generated by Django 5.0.3 on 2024-03-28 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacherinfos', '0028_dateseance_remove_seance_date_remove_seance_presence_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='IdSeance',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seance',
            name='Type',
            field=models.TextField(choices=[('Cours', 'Cours'), ('Td', 'Td'), ('Tp', 'Tp')], max_length=20),
        ),
    ]
