# Generated by Django 5.0.3 on 2024-03-29 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacherinfos', '0029_alter_seance_idseance_alter_seance_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salle',
            name='Zone',
            field=models.CharField(choices=[('Classe préparatoire', 'Classe préparatoire'), ('Seconde Cycle', 'Seconde Cycle')], max_length=20),
        ),
        migrations.AlterField(
            model_name='seance',
            name='Jour',
            field=models.CharField(choices=[('Dimanche', 'Dimanche'), ('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], max_length=20),
        ),
    ]
