# Generated by Django 5.0.3 on 2024-03-29 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacherinfos', '0030_alter_salle_zone_alter_seance_jour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='salle',
            name='IdSalle',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
