# Generated by Django 5.0.4 on 2024-04-25 22:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DateSeance',
            fields=[
                ('IddatteS', models.AutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(default=None, null=True)),
            ],
            options={
                'db_table': 'DateSeance',
            },
        ),
        migrations.CreateModel(
            name='Enseignant',
            fields=[
                ('Matricule', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('Nom', models.CharField(blank=True, max_length=20)),
                ('Prénom', models.CharField(blank=True, max_length=50)),
                ('DateNaissance', models.DateField(blank=True, null=True)),
                ('Adresse', models.CharField(blank=True, max_length=100)),
                ('Email', models.EmailField(blank=True, max_length=30)),
                ('NumeroTelephone', models.CharField(blank=True, max_length=20)),
                ('Fonction', models.CharField(choices=[('Fonction1', 'Fonction1'), ('Fonction2', 'Fonction2')], max_length=20)),
                ('Grade', models.CharField(choices=[('MCA', 'MCA'), ('MCB', 'MCB'), ('Teacher', 'Teacher'), ('LectureA', 'LectureA'), ('LectureB', 'LectureB'), ('Professor', 'Professor')], max_length=50)),
                ('Etablissement', models.CharField(blank=True, max_length=100)),
                ('MotDePasse', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'db_table': 'Enseignant',
            },
        ),
        migrations.CreateModel(
            name='Groupe',
            fields=[
                ('idGroupe', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('Numero', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10'), ('11', '11'), ('12', '12'), ('13', '13'), ('14', '14'), ('15', '15'), ('16', '16'), ('17', '17'), ('18', '18'), ('19', '19'), ('20', '20')], max_length=20)),
                ('Specialite', models.CharField(blank=True, choices=[('ISI', 'ISI'), ('SIW', 'SIW'), ('IASD', 'IASD')], max_length=20)),
            ],
            options={
                'db_table': 'Groupe',
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('NomPromo', models.CharField(choices=[('1CPI', '1CPI'), ('2CPI', '2CPI'), ('1CS', '1CS'), ('2CS', '2CS'), ('3CS', '3CS')], max_length=20, primary_key=True, serialize=False)),
                ('Departement', models.CharField(choices=[('Classe préparatoire', 'Classe préparatoire'), ('Seconde Cycle', 'Seconde Cycle')], max_length=20)),
            ],
            options={
                'db_table': 'Promotion',
            },
        ),
        migrations.CreateModel(
            name='Salle',
            fields=[
                ('NomSalle', models.CharField(blank=True, max_length=20)),
                ('IdSalle', models.AutoField(primary_key=True, serialize=False)),
                ('Zone', models.CharField(choices=[('Classe préparatoire', 'Classe préparatoire'), ('Seconde Cycle', 'Seconde Cycle')], max_length=20)),
                ('NbrPlaces', models.IntegerField(blank=True)),
                ('Type', models.CharField(choices=[('Amphi', 'Amphi'), ('SalleTd', 'SalleTd'), ('SalleTp', 'SalleTp')], max_length=20)),
            ],
            options={
                'db_table': 'Salle',
            },
        ),
        migrations.CreateModel(
            name='Abcence',
            fields=[
                ('IdAbs', models.AutoField(primary_key=True, serialize=False)),
                ('DateAbs', models.DateField(default=None)),
                ('HeureDebut', models.TimeField(blank=True)),
                ('HeureFin', models.TimeField(blank=True)),
                ('Motif', models.CharField(blank=True, max_length=100)),
                ('IdProf', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.enseignant')),
            ],
            options={
                'db_table': 'Absence',
            },
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('Code', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('NomModule', models.CharField(blank=True, max_length=20)),
                ('Coefficient', models.IntegerField(blank=True)),
                ('NbrHeures', models.IntegerField(blank=True)),
                ('Semestre', models.CharField(choices=[('S1', 'S1'), ('S2', 'S2')], max_length=20)),
                ('nomP', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.promotion')),
            ],
            options={
                'db_table': 'Module',
            },
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('IdSeance', models.AutoField(primary_key=True, serialize=False)),
                ('NomS', models.CharField(blank=True, max_length=20)),
                ('Type', models.TextField(choices=[('Cours', 'Cours'), ('Td', 'Td'), ('Tp', 'Tp')], max_length=20)),
                ('Jour', models.CharField(choices=[('Dimanche', 'Dimanche'), ('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], max_length=20)),
                ('HeureDebut', models.TimeField(blank=True)),
                ('HeureFin', models.TimeField(blank=True)),
                ('Semestre', models.CharField(choices=[('S1', 'S1'), ('S2', 'S2')], max_length=20)),
                ('Code', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.module')),
                ('Matricule', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.enseignant')),
                ('idGroupe', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.groupe')),
                ('idSalle', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.salle')),
            ],
            options={
                'db_table': 'Seance',
            },
        ),
        migrations.CreateModel(
            name='heure',
            fields=[
                ('idHeure', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('defType', models.CharField(choices=[('HeuresSup', 'HeuresSup'), ('Charge', 'Charge')], max_length=20)),
                ('idSeance', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.seance')),
            ],
            options={
                'db_table': 'Heure',
            },
        ),
        migrations.CreateModel(
            name='Seances',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.dateseance')),
                ('idSeance', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.seance')),
            ],
            options={
                'db_table': 'Seances',
            },
        ),
        migrations.CreateModel(
            name='section',
            fields=[
                ('idSection', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('NomSection', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=20)),
                ('nomP', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.promotion')),
            ],
            options={
                'db_table': 'Section',
            },
        ),
        migrations.AddField(
            model_name='seance',
            name='idSection',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.section'),
        ),
        migrations.AddField(
            model_name='groupe',
            name='idSection',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.section'),
        ),
        migrations.CreateModel(
            name='Specialite',
            fields=[
                ('idSpecialite', models.IntegerField(blank=True, primary_key=True, serialize=False)),
                ('NomSpecialite', models.CharField(blank=True, choices=[('ISI', 'ISI'), ('SIW', 'SIW'), ('IASD', 'IASD')], max_length=20)),
                ('idSection', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.section')),
            ],
            options={
                'db_table': 'Specialite',
            },
        ),
        migrations.AddField(
            model_name='seance',
            name='idSpecialite',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.specialite'),
        ),
        migrations.CreateModel(
            name='Enseigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Matric', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.enseignant')),
                ('Codee', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.module')),
            ],
            options={
                'db_table': 'Enseigne',
                'unique_together': {('Matric', 'Codee')},
            },
        ),
        migrations.CreateModel(
            name='SpecPromo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idSpecialite', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.specialite')),
                ('nomP', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.promotion')),
            ],
            options={
                'db_table': 'SpecPromo',
                'unique_together': {('idSpecialite', 'nomP')},
            },
        ),
    ]
