# Generated by Django 5.0.4 on 2024-05-12 07:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='EcoleAdministartion',
            new_name='EcoleAdministration',
        ),
        migrations.AlterModelTable(
            name='ecoleadministration',
            table='EcoleAdministration',
        ),
    ]
