# Generated by Django 5.0.4 on 2024-05-11 11:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seance',
            name='idSpecialite',
        ),
        migrations.RemoveField(
            model_name='specialite',
            name='idSection',
        ),
        migrations.AddField(
            model_name='seance',
            name='idPromo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.promotion'),
        ),
        migrations.AddField(
            model_name='seances',
            name='present',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='abcence',
            name='DateAbs',
            field=models.DateField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='abcence',
            name='HeureDebut',
            field=models.TimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='abcence',
            name='HeureFin',
            field=models.TimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='abcence',
            name='Motif',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='Numero',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='Specialite',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='seance',
            name='Code',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.module'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='Semestre',
            field=models.CharField(choices=[('S1', 'S1'), ('S2', 'S2')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='seance',
            name='idGroupe',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.groupe'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='idSalle',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.salle'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='idSection',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.section'),
        ),
        migrations.AlterField(
            model_name='section',
            name='NomSection',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='specialite',
            name='NomSpecialite',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='specialite',
            name='idSpecialite',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='SpecSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idSection', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.section')),
                ('idSpecialite', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.specialite')),
            ],
            options={
                'db_table': 'SpecSection',
                'unique_together': {('idSpecialite', 'idSection')},
            },
        ),
    ]
