# Generated by Django 5.0.4 on 2024-05-11 13:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_remove_seance_idspecialite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='Fonction',
            field=models.CharField(choices=[('fonction1', 'fonction1'), ('fonction2', 'fonction2')], max_length=20),
        ),
    ]
