# Generated by Django 5.0.4 on 2024-04-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_alter_seance_idspecialite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abcence',
            name='DateAbs',
            field=models.DateField(default=None, null=True),
        ),
    ]
