# Generated by Django 5.0.4 on 2024-05-12 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0002_rename_ecoleadministartion_ecoleadministration_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='EcoleAdministration',
        ),
    ]
