# Generated by Django 5.0.4 on 2024-04-27 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_alter_abcence_dateabs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abcence',
            name='HeureDebut',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abcence',
            name='HeureFin',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='abcence',
            name='Motif',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
