# Generated by Django 5.0.4 on 2024-05-12 12:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_delete_ecoleadministration'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoleAdministration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matricule', models.CharField(max_length=20)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('mot_de_passe', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'EcoleAdministration',
            },
        ),
        migrations.CreateModel(
            name='Montant',
            fields=[
                ('idMontant', models.AutoField(primary_key=True, serialize=False)),
                ('typeRecu', models.CharField(choices=[('Banque', 'Banque'), ('CCP', 'CCP')], max_length=20)),
                ('somme', models.FloatField(default=None)),
                ('anneeUniversiatire', models.CharField(default=None, max_length=50)),
                ('semestre', models.CharField(choices=[('S1', 'S1'), ('S2', 'S2')], max_length=20)),
                ('matricule', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.enseignant')),
            ],
            options={
                'db_table': 'Montant',
            },
        ),
    ]
