# Generated by Django 5.0.4 on 2024-05-11 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0003_alter_enseignant_fonction'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enseignant',
            name='Fonction',
            field=models.CharField(choices=[('Fonction1', 'Fonction1'), ('Fonction2', 'Fonction2')], max_length=20),
        ),
    ]
