# Generated by Django 5.0.4 on 2024-04-27 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_alter_abcence_heuredebut_alter_abcence_heurefin_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abcence',
            name='DateAbs',
            field=models.DateField(default=None),
        ),
        migrations.AlterField(
            model_name='abcence',
            name='HeureDebut',
            field=models.TimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='abcence',
            name='HeureFin',
            field=models.TimeField(blank=True, default=None),
        ),
        migrations.AlterField(
            model_name='abcence',
            name='Motif',
            field=models.CharField(blank=True, default=None, max_length=100),
        ),
    ]
