# Generated by Django 5.0.4 on 2024-05-12 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_ecoleadministration_montant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='montant',
            name='typeRecu',
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='Grade',
            field=models.CharField(choices=[('MCA', 'MCA'), ('MCB', 'MCB'), ('LectureA', 'LectureA'), ('LectureB', 'LectureB'), ('Professor', 'Professor')], max_length=50),
        ),
    ]
