# Generated by Django 5.0.4 on 2024-05-11 14:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0004_alter_enseignant_fonction'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='idSpecialite',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.specialite'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='idGroupe',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.groupe'),
        ),
    ]
