# Generated by Django 5.0.4 on 2024-05-11 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_seance_idspecialite_alter_seance_idgroupe'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seance',
            name='idSpecialite',
        ),
    ]
