# Generated by Django 5.0.4 on 2024-05-12 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0005_remove_montant_typerecu_alter_enseignant_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='ecoleadministration',
            name='Email',
            field=models.EmailField(blank=True, max_length=30),
        ),
    ]
