# Generated by Django 5.0.4 on 2024-05-12 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_ecoleadministration_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ecoleadministration',
            name='id',
        ),
        migrations.AlterField(
            model_name='ecoleadministration',
            name='matricule',
            field=models.CharField(blank=True, max_length=20, primary_key=True, serialize=False),
        ),
    ]
