# Generated by Django 5.0.4 on 2024-05-13 15:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_remove_seance_idspecialite'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcoleAdministration',
            fields=[
                ('matricule', models.CharField(blank=True, max_length=20, primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('mot_de_passe', models.CharField(max_length=20)),
                ('Email', models.EmailField(blank=True, max_length=30)),
            ],
            options={
                'db_table': 'EcoleAdministration',
            },
        ),
        migrations.AddField(
            model_name='heure',
            name='duree',
            field=models.DurationField(null=True),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='Grade',
            field=models.CharField(choices=[('MCA', 'MCA'), ('MCB', 'MCB'), ('LectureA', 'LectureA'), ('LectureB', 'LectureB'), ('Professor', 'Professor')], max_length=50),
        ),
        migrations.AlterField(
            model_name='heure',
            name='idHeure',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='seance',
            name='idGroupe',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.groupe'),
        ),
        migrations.AlterUniqueTogether(
            name='seances',
            unique_together={('date', 'idSeance')},
        ),
        migrations.CreateModel(
            name='Montant',
            fields=[
                ('idMontant', models.AutoField(primary_key=True, serialize=False)),
                ('somme', models.FloatField(default=None)),
                ('anneeUniversiatire', models.CharField(default=None, max_length=50)),
                ('semestre', models.CharField(choices=[('S1', 'S1'), ('S2', 'S2')], max_length=20)),
                ('matricule', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.enseignant')),
            ],
            options={
                'db_table': 'Montant',
            },
        ),
    ]
