# Generated by Django 5.0.4 on 2024-04-28 16:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0006_alter_abcence_dateabs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seance',
            name='idSpecialite',
        ),
        migrations.AddField(
            model_name='seance',
            name='idAbs',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.abcence'),
        ),
        migrations.AddField(
            model_name='seance',
            name='idPromo',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.promotion'),
        ),
    ]
