# Generated by Django 5.0.4 on 2024-05-15 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_ecoleadministration_heure_duree_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ecoleadministration',
            old_name='mot_de_passe',
            new_name='MotDePasse',
        ),
    ]
