# Generated by Django 5.0.4 on 2024-06-04 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0007_remove_ecoleadministration_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='montant',
            name='irg',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='montant',
            name='montant_debite',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='montant',
            name='montant_net',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='montant',
            name='nombre_des_heures',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='montant',
            name='periode',
            field=models.CharField(choices=[('S1', 'S1'), ('S2', 'S2')], default=None, max_length=20),
        ),
        migrations.AddField(
            model_name='montant',
            name='prix_unitaire',
            field=models.FloatField(default=None),
        ),
        migrations.AddField(
            model_name='montant',
            name='securite_sociale',
            field=models.FloatField(default=None),
        ),
    ]
