# Generated by Django 5.0.4 on 2024-04-28 20:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_alter_seance_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='Semestre',
            field=models.CharField(choices=[('S1', 'S1'), ('S2', 'S2')], default=None, max_length=20),
        ),
        migrations.AlterField(
            model_name='seance',
            name='idSalle',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.salle'),
        ),
    ]
