# Generated by Django 5.0.4 on 2024-06-04 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0008_montant_irg_montant_montant_debite_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='montant',
            old_name='somme',
            new_name='montant_total',
        ),
    ]
