# Generated by Django 5.0.4 on 2024-04-28 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_alter_seance_semestre_alter_seance_idsalle'),
    ]

    operations = [
        migrations.AddField(
            model_name='seances',
            name='present',
            field=models.BooleanField(default=True),
        ),
    ]
