# Generated by Django 5.0.4 on 2024-06-04 19:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0009_rename_somme_montant_montant_total'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reclamation',
            fields=[
                ('IdRec', models.AutoField(primary_key=True, serialize=False)),
                ('description', models.CharField(default=None, max_length=255)),
                ('enseignant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Admin.enseignant')),
            ],
            options={
                'db_table': 'Reclamation',
            },
        ),
    ]
