# Generated by Django 5.0.4 on 2024-04-28 21:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0010_seances_present'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='seance',
            name='idAbs',
        ),
    ]
