# Generated by Django 5.0.4 on 2024-05-15 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0011_alter_section_idsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='idSection',
            field=models.AutoField(default=0, primary_key=True, serialize=False),
        ),
    ]
