# Generated by Django 5.0.4 on 2024-04-28 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0012_alter_specialite_idsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='idGroupe',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.groupe'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='idSection',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.section'),
        ),
    ]
