# Generated by Django 5.0.4 on 2024-04-29 19:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0013_alter_seance_idgroupe_alter_seance_idsection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='specialite',
            name='idSection',
        ),
        migrations.CreateModel(
            name='SpecSection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idSection', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.section')),
                ('idSpecialite', models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.specialite')),
            ],
            options={
                'db_table': 'SpecSection',
                'unique_together': {('idSpecialite', 'idSection')},
            },
        ),
    ]
