# Generated by Django 5.0.4 on 2024-04-29 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0014_remove_specialite_idsection_specsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='Specialite',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='specialite',
            name='NomSpecialite',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
