# Generated by Django 5.0.4 on 2024-04-29 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0015_alter_groupe_specialite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='specialite',
            name='idSpecialite',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
