# Generated by Django 5.0.4 on 2024-05-15 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0015_alter_section_idsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='nomP',
            field=models.CharField(choices=[('1CPI', '1CPI'), ('2CPI', '2CPI'), ('1CS', '1CS'), ('2CS', '2CS'), ('3CS', '3CS')], max_length=20),
        ),
    ]
