# Generated by Django 5.0.4 on 2024-05-15 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0016_alter_section_nomp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='nomP',
            new_name='nomP_id',
        ),
    ]
