# Generated by Django 5.0.4 on 2024-04-29 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0016_alter_specialite_idspecialite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='groupe',
            name='Numero',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='section',
            name='NomSection',
            field=models.CharField(max_length=20),
        ),
    ]
