# Generated by Django 5.0.4 on 2024-05-15 16:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0017_rename_nomp_section_nomp_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='section',
            name='nomP_id',
        ),
        migrations.AddField(
            model_name='section',
            name='nomP',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.DO_NOTHING, to='Admin.promotion'),
        ),
    ]
