# Generated by Django 5.0.4 on 2024-05-15 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0019_rename_nomp_section_nomp_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='section',
            old_name='nomP_id',
            new_name='nomP',
        ),
    ]
