# Generated by Django 5.0.4 on 2024-05-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0020_rename_nomp_id_section_nomp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='idSection',
            field=models.AutoField(default=6, primary_key=True, serialize=False),
        ),
    ]
