# Generated by Django 5.0.4 on 2024-05-15 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0021_alter_section_idsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='idSection',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
