# Generated by Django 5.0.4 on 2024-05-31 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0026_alter_section_idsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='idSection',
            field=models.IntegerField(blank=True, primary_key=True, serialize=False),
        ),
    ]
