# Generated by Django 5.0.4 on 2024-06-05 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0028_rename_somme_montant_irg_montant_montant_debite_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ecoleadministration',
            name='Email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='ecoleadministration',
            name='matricule',
            field=models.CharField(blank=True, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='ecoleadministration',
            name='mot_de_passe',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ecoleadministration',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ecoleadministration',
            name='prenom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='Email',
            field=models.EmailField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='Fonction',
            field=models.CharField(choices=[('Fonction1', 'Fonction1'), ('Fonction2', 'Fonction2')], max_length=255),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='Grade',
            field=models.CharField(choices=[('Professeur', 'Professeur'), ('MCA', 'MCA'), ('MCB', 'MCB'), ('MAA', 'MAA'), ('MAB', 'MAB')], max_length=255),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='Matricule',
            field=models.CharField(blank=True, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='MotDePasse',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='Nom',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='NumeroTelephone',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='enseignant',
            name='Prénom',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='Numero',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='groupe',
            name='Specialite',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='heure',
            name='defType',
            field=models.CharField(choices=[('HeuresSup', 'HeuresSup'), ('Charge', 'Charge')], max_length=255),
        ),
        migrations.AlterField(
            model_name='module',
            name='Code',
            field=models.CharField(blank=True, max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='module',
            name='NomModule',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='module',
            name='Semestre',
            field=models.CharField(choices=[('S1', 'S1'), ('S2', 'S2')], max_length=255),
        ),
        migrations.AlterField(
            model_name='montant',
            name='anneeUniversiatire',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='montant',
            name='periode',
            field=models.CharField(choices=[('S1', 'S1'), ('S2', 'S2')], default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='montant',
            name='semestre',
            field=models.CharField(choices=[('S1', 'S1'), ('S2', 'S2')], max_length=255),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='Departement',
            field=models.CharField(choices=[('Classe préparatoire', 'Classe préparatoire'), ('Seconde Cycle', 'Seconde Cycle')], max_length=255),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='NomPromo',
            field=models.CharField(choices=[('1CPI', '1CPI'), ('2CPI', '2CPI'), ('1CS', '1CS'), ('2CS', '2CS'), ('3CS', '3CS')], max_length=255, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='salle',
            name='NomSalle',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='salle',
            name='Type',
            field=models.CharField(choices=[('Amphi', 'Amphi'), ('SalleTd', 'SalleTd'), ('SalleTp', 'SalleTp')], max_length=255),
        ),
        migrations.AlterField(
            model_name='salle',
            name='Zone',
            field=models.CharField(choices=[('Classe préparatoire', 'Classe préparatoire'), ('Seconde Cycle', 'Seconde Cycle')], max_length=255),
        ),
        migrations.AlterField(
            model_name='seance',
            name='Jour',
            field=models.CharField(choices=[('Dimanche', 'Dimanche'), ('Lundi', 'Lundi'), ('Mardi', 'Mardi'), ('Mercredi', 'Mercredi'), ('Jeudi', 'Jeudi'), ('Vendredi', 'Vendredi'), ('Samedi', 'Samedi')], max_length=255),
        ),
        migrations.AlterField(
            model_name='seance',
            name='NomS',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='seance',
            name='Semestre',
            field=models.CharField(choices=[('S1', 'S1'), ('S2', 'S2')], default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='seance',
            name='Type',
            field=models.TextField(choices=[('Cours', 'Cours'), ('Td', 'Td'), ('Tp', 'Tp')], max_length=255),
        ),
        migrations.AlterField(
            model_name='section',
            name='NomSection',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='specialite',
            name='NomSpecialite',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
