# Generated by Django 5.0.4 on 2024-06-05 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Admin', '0029_alter_ecoleadministration_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evenement',
            fields=[
                ('idEv', models.AutoField(primary_key=True, serialize=False)),
                ('nomEv', models.CharField(default=None, max_length=255)),
                ('dateDébut', models.DateField(blank=True, default=None)),
                ('dateFin', models.DateField(blank=True, default=None)),
            ],
            options={
                'db_table': 'Evenement',
            },
        ),
    ]
